web:
  build: .
  command: sh -c "npm install; npm start"
  ports:
    - "4040:4040"
  volumes:
    - /home/alexis/Escritorio/api_3/api:/api
  links:
   - "db:redis_3"

db:
  image: redis
  ports:
    - "6379:6379"